name: Playwright Tests
on:
  workflow_dispatch:
    inputs:
      environment_variant:
        type: choice
        description: Select environment to run automation (should use production). 
        required: true
        default: production
        options:
          - dev
          - production
          - uat
      country_variant:
        type: choice
        description: Select country to run with localization. 
        required: true
        default: singapore
        options:
          - singapore
          - vietnam

jobs:
  automation-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: "https://npm.pkg.github.com"
      - name: Install dependencies
        run: |
          npm install
      - name: Install Playwright Browsers
        run: |
          npx playwright install --with-deps
      - name: Install Cross Environment
        run: |
          npm install -g cross-env
      - name: Run Playwright tests
        run: |
          cross-env test_env=${{inputs.environment_variant}} country=${{inputs.country_variant}} npx playwright test --grep @exportJsonFile
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: test-output/html/index.html
          retention-days: 30
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: weather-information
          path: weather/*.json
          retention-days: 30
